
name: Python Game CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Python 3.7
      - name: Setup Python 3.7.1
        uses: actions/setup-python@v4
        with:
          python-version: "3.7.1"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame==1.9.*

      # 4. Run basic validation
      # (We avoid opening the game window in CI; instead check import + script sanity)
      - name: Validate game starts
        run: |
          python - << 'EOF'
          import pygame
          print("Pygame version:", pygame.ver)
          import main
          print("main.py imported successfully ✅")
          EOF

