name: Python Pygame CI (container python:3.7)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: python:3.7

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pip deps (inside container)
        run: |
          python -m pip install --upgrade pip
          pip install pygame==1.9.*

      - name: Validate (headless import)
        env:
          SDL_VIDEODRIVER: dummy
        run: |
          python - <<'PY'
          import pygame
          print("Pygame:", getattr(pygame, "__version__", pygame.version.ver))
          import main
          print("main.py imported successfully ✅")

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}          
